### ISSUE TITLE
Graves disappearing

### ISSUE THREAD

**Issue by Gaara23** [p3t3rix/VsGraveMod#3]
So like the title says I've had issues for a while now where I'll be in a mine/cave/the edge of a block and get killed by say a Drifter or something and when I go to my death point the grave and all of my stuff are just gone. I've looked in the logs and don't see anything wrong upon first inspection but this has happened a few times and gets very annoying. Especially when you've gotten a lot of highly needed materials that are pretty rare.

**Comment by p3t3rix** [comment]
if there is no grave you should not lose any items (because when a player joins it sets the death behavior to keep). The range where it looks for a suitable spot is 3x3 as far as i remember. Without a specific reproduction scenario it is difficult for me to debug these. 

Because i don't really maintain this mod anymore i would suggest this as an alternative https://mods.vintagestory.at/playercorpse
There you have the option to restore player items in case something with grave placement goes wrong
